<?php include $_SERVER['DOCUMENT_ROOT'].'/shared/header.php';?>
<div id="wrapper">
    <div class="container">
        <div class="col-md-12">
            <div class="page-header">
                <h1>TAP Series Privacy Policy</h1>
            </div>
			<br />
            <div class="row">
                <span class="subtitle"><a href="privacys">Español (Oprima Aqui)</a></span><br>
                <p align="left"><span class="subtitle">GENERAL INFORMATION ABOUT THE POLICY OF THIS WEBSITE IN ITS COLLECTION, PROTECTION, USE AND DISCLOSURE OF THE PERSONAL INFORMATION GATHERED ON THIS SITE.</span><br><br>
                This website, Tapseries.com (the "Site"), is owned and operated Tap Series, LLC. ("TAP"). TAP recognizes the importance protecting the privacy of Personally Identifiable Information we obtain through our site.
                <br><br><span class="subtitle">LINKS TO OTHER SITES</span><br><br>
                Links from this site can take you to third party websites or resources. This Privacy Statement or any other policies or terms of this Site do not cover the information practices of third party websites. Be sure that you know the terms of use and privacy policy of any linked website before using it.
                <br><br><span class="subtitle">WHAT PERSONAL INFORMATION DO WE COLLECT AND USE</span><br><br>
                We consider the following to be examples of Personally Identifiable Information but there may be others: your first and last name, email address, home address, and phone number.<br><br>
                TAP does not collect Personally Identifiable Information about a user unless it is voluntarily provided to our Company and so that we can serve the user's needs.  TAP Series will not be liable for users failing to safeguard their user name and password from others, and will not be liable to users for special, indirect, or consequential damages.
                <br><br><span class="subtitle">INFORMATION SHARING AND DISCLOSURE</span><br><br>
                Except as specifically stated in this statement, our policy is not to share the Personally Identifiable Information collected through this Site with third parties, but we may share this Personally Identifiable Information with affiliates of TAP and other companies and organizations who perform work for us under contract or sell products or services that complement our products and services. We also may disclose Personally Identifiable Information (a) in response to a subpoena, court order or legal process, to the extent permitted and required by law; (b) to protect user security or the security of other persons, consistent with applicable laws; or (c) in connection with a sale, joint venture or other transfer to some or all of TAP or the assets of TAP.<br><br>
                Our "course management features" provide materials and services to instructors and students for purposes of specific courses or testing, and may display the names, email addresses, grades and log-in information and make them available to school administrators. Instructors can use student email addresses for communication with students regarding the course, and administrators may store personal data generated by the course site tools for the purpose of maintaining educational records or other legitimate educational purposes.
                <br><br><span class="subtitle">COLLECTION AND USE OF INFORMATION FROM COOKIES</span><br><br>
                Our Site uses "cookies" to obtain certain types of information when your Web browser accesses the Site.   Cookies are textual identifiers that our systems transfer to your computer's hard drive through your Web browser to enable our Site to recognize your browser, and to optimize and sometimes customize your use of our Site. If you want to disable cookies, you can. The Help portion of the toolbar on most browsers and "add-on" programs will tell you how to prevent your browser from accepting new cookies, how to have the browser notify you when you receive a new cookie, or how to disable cookies altogether. It is your choice, but cookies allow you to take full advantage of this Site's features, and we recommend that you leave them turned on.<br><br>
                We do not use cookies to get users' Personally Identifiable Information before a user registers with our Site and affirmatively opts-in. Once a user opts-in and provides personal information for purposes of receiving more information from us, we do collect and use that information obtained through the cookie technology for purposes of marketing to you, in accordance with this policy. If you do not want to receive e-mail or other marketing communications from us, you can opt out of further marketing to the addresses you have provided.<br><br>
                TAP reserves the right to monitor your use of the site to determine if you are complying with our terms and the right, in its sole discretion, to terminate your access to the Site. Please note that this Privacy Statement may be revised by TAP from time to time. If that happens, we will post the revised policy here. Revisions are effective upon posting and your continued use of this Site after the posting will be subject to the changed terms of the revisions.
                <br><br><span class="subtitle">POLICIES AND PROCEDURES FOR COMPLYING WITH AMERICANS WITH DISABILITIES ACT</span><br><br>
                TAP Series complies with the Americans with Disabilities Act (ADA). The  Food Handler Card law does not prohibit a stakeholder from having assistance in the study of the course and examination. The stakeholder may have another party read, translate or operate the computer. There are no special medical requests needed. The stakeholder may not have assistance with the actual selection of the examination answers. The stakeholder may communicate the answer to the other party to click the chosen answer.  Any needs outside of these policies and procedures are not anticipated. Stakeholders protected by the Americans with Disabilities Act do not need permission from TAP Series prior to purchasing or taking the course and examination. The Food Handler Training is provided through secured servers.

                <br><br><a name="accessibility"></a> <span class="subtitle">Accessibility Policy</span><br><br>
                TAP Series is committed to ensuring the accessibility of its website for people with disabilities. TAP Series shall ensure accessibility to Electronic and Information Technology (EIT) for individuals with disabilities in compliance with the Americans with Disabilities Act of 1990, and all other applicable statute and regulations.  Any issues should be reported to techsupport@tapseries.com.

                <br><br><span class="subtitle">Non-Discrimination</span><br><br>

                TAP Series policies and procedures do not discriminate on the basis of race, color, religion, sexual orientation, national origin, ancestry, disability, age or use of leave protected by the Family and Medical Leave Act with regards its Food Handler Training, activities, or with regards to employment.
                <br><br><span class="subtitle">OBTAINING ADDITIONAL INFORMATION ABOUT PRIVACY</span><br><br>
                If you have any concerns or questions about privacy on this Site, please email us at info@tapseries.com or call 888-826-5222.
                <br><br> <font size="1">Copyright © TAP Series, LLC </font></p>
            </div>
			<br />
        </div>        
    </div>
</div>
<?php include $_SERVER['DOCUMENT_ROOT'].'/shared/footer.php';?>
</body>
</html>